[project]
title = "Preswald Project"
version = "0.1.0"
port = 8501
slug = "shakinglens-148104"  
entrypoint = "hello.py"    

[branding]
name = "Shaking Lens"
logo = "images/shaking_lens_logo.png"
favicon = "images/shaking_lens_logo.png"
primaryColor = "#E0CBA8"

[data.wildfire_rcp_dataset]
type = "csv"
path = "data/Wildfire_RCP_Dataset.csv"

[logging]
level = "INFO"
format = "%(asctime)s - %(name)s - %(levelname)s - %(message)s"